- README.md
This add entry adds Prolog language and its implementation SWI-Prolog. SWI-Prolog has been ported to WebAssembly. Demo: <http://demos.rlaanemets.com/swi-prolog-wasm/example/>
> Add Prolog

- README.md
The informative repository was copied directly under the SWI-Prolog organization. Follows up PR #17.
> SWI-Prolog WebAssembly link change

- README.md
F# compiles to WebAssembly through Bolero (fsbolero.io). Also enhanced C# support by mentions Blazor.
> Added F# language support. Enhanced C# description with Blazor reference

- README.md
Hey stranger 👋 ,
awesome repo you've got here (bad joke)
> docs: fixed a typo in `Rust/Woz` section

- README.md
[ElixirWasm](https://github.com/jamen/elixir-wasm) and [HaskellWasm](https://github.com/sdiehl/wasm) are now archived and unmaintained
Xlang got renamed to [Co](https://github.com/rsms/xlang)
> update doc, mark 2 as unmaintained

- README.md
This is a F# native way to create WASM apps and uses Blazor underneath.
> Add Bolero to .NET list

- README.md
The Schism URL was pointing to an archived version of the repository. This PR
updates the link to point to the new version.
> Update Schism URL

- README.md
This PR adds a link to [Javy](https://github.com/shopify/javy), which is a tool that can be used to generate WASI-compatible Wasm modules with JavaScript code.
> Add Javy to JavaScript section

- README.md
Changing the main repository link because it was added to as a branch to nBallerina repository.
> Update Ballerina wasm compiler

- README.md
The current C# / .NET options are largely limited to Blazor and variants thereof (e.g. a runtime targeting WASM that executes .NET CIL); NativeAOT-LLVM looks to be a promising alternative that compiles directly to WASM, removing the overhead of another executor. Think it's worth including here.
> .NET: mention NativeAOT-LLVM

- README.md
These projects seem to have migrated their git repos to other platforms, I updated the links on the main README.
> Update links for migrated repos

- README.md
Add KCL language. KCL is a constraint-based record & functional language mainly used in configuration and policy scenarios.
https://github.com/KusionStack/KCLVM
> feat: add KCL language.

- README.md
The linked [PR](https://github.com/crystal-lang/crystal/pull/10870) for crystal was merged and released in crystal version [1.4.0](https://crystal-lang.org/2022/04/06/1.4.0-released.html)
I found out as I recently saw this [article](https://glue.im/noah/introduction-to-webassembly-in-crystal) demonstrating it.
> Change status of crystal

- README.md
Add Rego language, and links to SDKs for working with Rego policies compiled to Wasm.
Signed-off-by: Anders Eknert <anders@eknert.com>
> Add Rego language

- README.md
Definitely usable in it's current state (especially compared to the others in the list).
> Update status for Grain

- README.md
Featuring [dart2wasm](https://dart.dev/web/js-interop)
Fixes #97
> Add Dart to the list

- README.md
Added R-lang, Vlang, "official" ruby.wasm. 
Also compilers: rlang (Ruby-like-language-to-WASM), and rpython, tpython (Python-like-language-to-WASM).
Resolves https://github.com/appcypher/awesome-wasm-langs/issues/104 .
BTW Thank you @appcypher for your awesome lists!
> Added R, V, ruby.wasm, rlang, rpython, tpython

- README.md
Cheerp is up-to-date with LLVM upstream, barring a few months, so "up to C++14" was out-of-date
> Update Cheerp compiler description

- README.md
fixes #130 
Also i think rest of the categories require state update as some of the languages have gotten better stability while some have been unmaintained and deprecated.
languages like never & cobaul havent been updated in years yet they are tagged "stable" . IMHO languages that havent been updated in 9months should move towards the unmaintained category.
> fix #130 producation & unmaintained Categorization

- README.md
Wa-lang is unstable but usable.
- NES emulator: https://wa-lang.org/nes/
- https://github.com/wa-lang/nes
- WebGPU Demo (Only support PC/Chrome): https://wa-lang.org/webgpu/
- https://github.com/wa-lang/webgpu
Wa talk on KCD(Chinese): https://wa-lang.org/smalltalk/st0036.html
> Update status for Wa

- README.md
Adds the top-level LabVIEW category and two associated projects for running the LabVIEW G graphical programming language in WebAssembly
> Add LabVIEW category and associated projects

- README.md
Added Boa, Goja, Otto to JavaScript section.
* Boa - [presents](https://github.com/boa-dev/boa#live-demo-wasm) a WASM-based [playground](https://boajs.dev/boa/playground/)
* Goja - An oversimplified [example](https://github.com/wasm-outbound-http-examples/js-in-go/blob/7ed91aaa8dad2cb322a4dddab8df76a9194dfe8f/browser-and-deno-goja/main.go#L7) is available. This small progam embeds a goja VM as library and a JS code as string. After compiling to WASM, this program results to a single WASM file and works well in browsers and Deno+Bun. Browser demo is [here](https://wasm-outbound-http-examples.github.io/js-in-go/goja/)
* Otto - An oversimplified [example](https://github.com/wasm-outbound-http-examples/js-in-go/blob/7ed91aaa8dad2cb322a4dddab8df76a9194dfe8f/browser-and-deno-otto/main.go#L7) is …
> Added Boa, Goja, Otto to JS section

- README.md
Added NerdLang, RingLang, and Wonkey sections.
Added Guile Hoot to Scheme section.
* Guile Hoot - [declared](https://gitlab.com/spritely/guile-hoot#guile-hoot) as `Guile->WebAssembly
project`. It's usable enough to [build interactive web pages](https://spritely.institute/news/building-interactive-web-pages-with-guile-hoot.html), and more.
* Nerd - [declares](https://github.com/NerdLang/nerd/blob/400b367708c2fee58060f85fb8546a522c8add9c/README.md?plain=1#L133) WASM as supported platform. Has an JS-interop [example](
https://github.com/NerdLang/nerd/blob/400b367708c2fee58060f85fb8546a522c8add9c/example/wasm_binding.ng#L8). I've tested that example and it worked as expected. (But "compiler" itself needs to be patched to work on case-sensitive filesystem).
* Ring - …
> Added Guile Hoot, NerdLang, RingLang, and Wonkey

- README.md
Added basic_rs, basicwasm, EndBASIC, and gobasic to new BASIC section.
* basic_rs - [declares](https://github.com/yiransheng/basic_rs/blob/ddd64e2eacfc2b36354e32e2b6abdb97989bd3a2/basic2wasm/README.md) WASM support and has Game of Life [demo](http://subdued-afternoon.surge.sh) compiled from BASIC [source](https://github.com/yiransheng/basic_rs/blob/ddd64e2eacfc2b36354e32e2b6abdb97989bd3a2/basic2wasm/example/source.bas).
* basicwasm - Built and tested its web REPL. At least `PRINT`, `LOCATE`, `CLS`, `COLOR` commands work well.
* EndBASIC - [advertises](https://github.com/endbasic/endbasic/blob/endbasic-0.10.0/repl/examples/tour.bas#L61-L62) WASM support and provides a [web REPL](https://github.com/endbasic/endbasic/blob/endbasic-0.10.0/web/README.md?plain=1#L28) as demo …
> Added basic_rs, basicwasm, EndBASIC, gobasic to new BASIC section

- README.md
Adds ThetaLang to the list.
[Theta](https://github.com/alexdovzhanyn/ThetaLang) is a general purpose, strongly typed, functional programming language that compiles to WebAssembly using Binaryen
> Add ThetaLang

- README.md
Added MoonBit-lang.
**Proofs**
* [Declares](https://www.moonbitlang.com/) "`Moonbit language designed specifically for WebAssembly`".
* Has demos/examples, e.g. [CloudFlare Worker](https://github.com/moonbitlang/moonbit-docs/tree/813f4b2c8b5cf006fdfcb1b6fea8fca9281f761e/examples/cf_worker#moonbits-cloudflare-worker-demo) one.
> Added MoonBit

- README.md
Added Janet-lang, a "modern Lisp".
* Janet can be [compiled](https://github.com/janet-lang/janet-lang.org/blob/e4a7d558caee6e2ebcfd3f9c0ac000511f36f6e1/Makefile#L29-L37) to WASM using Emscripten. Interpreter WASM binary file size is about 1Mb.
* Has WASM-enabled [playground](https://janet-lang.org/#Try-It), also [secondary WASM-enabled playground](https://janetdocs.com/playground).
> Added Janet

- README.md
The [WebAssemblyCompiler.jl](https://tshort.github.io/WebAssemblyCompiler.jl/stable/) project is still experimental at the moment, but it seems like the most promising approach so far for Julia to target Wasm using the newer Wasm GC extension.
> Add WebAssemblyCompiler.jl to Julia section

- README.md
Added The Berry Script Language.
* Berry can be compiled to WASM using Emscripten, just need a change in the [Makefile](https://github.com/berry-lang/berry_web/blob/9ebc4e2d0945e6ea5e58daba4bc747a44df5a02c/Makefile#L6) from `-s WASM=0` to `-s WASM=1`.  Interpreter WASM binary file size is about 1Mb, and non-Asyncify version is about 270k.
> Added Berry

- README.md
Added Ren-C and Rye to new Rebol section.
* Ren-C officially [focuses](https://github.com/metaeducation/ren-c/blob/8516f0fca8ddce40a97e7647a087dc55e065cf3b/README.md?plain=1#L23-L24) on WASM, and has workflows to build [WASM/Emscripten](https://github.com/metaeducation/ren-c/blob/8516f0fca8ddce40a97e7647a087dc55e065cf3b/.github/workflows/web-build.yml#L6) and [WASI](https://github.com/metaeducation/ren-c/blob/8516f0fca8ddce40a97e7647a087dc55e065cf3b/.github/workflows/wasi-build.yml#L6-L8) versions.
* Rye officially [supports](https://github.com/refaktor/rye/tree/v0.0.32#build-wasm-version) building a WASM version. Also it has a WASM-powered playground on [ryelang.org](https://ryelang.org) website (grey `Rye console` button on top-right).
> Added Ren-C and Rye to new Rebol section

- README.md
Added Jint, Porffor, and sebastianwessel-quickjs to JavaScript section.
* Jint 
- implemented in pure C#. Can be embedded to .Net program, which compiles to WASM seamlessly (tested it).
* Porffor - it's experimental and alpha, but unique and very promising.
- [declares](https://github.com/CanadaHonk/porffor/blob/5e26327fba507fb17f658aff02e14bd6912da3de/README.md#compiling-to-wasm) support to compile JS to WASM.
- has a [playground](https://porffor.dev/) at the bottom of page, there it compiles JS snippets to WAT and C.
* sebastianwessel-quickjs
- [declares](https://github.com/sebastianwessel/quickjs/tree/v2.0.1?tab=readme-ov-file#quickjs---execute-javascript-and-typescript-in-a-webassembly-quickjs-sandbox) itself as a WASM sandbox for executing JS/TS.
- has a WASM-enabled …
> Added Jint, Porffor, and sebastianwessel-quickjs to JavaScript section
