appcypher/awesome-wasm-langs

README.md
Added a link to my implementation of the Forth programming language targeting wasm.
=> Add Forth programming language

README.md
The Blazor repo has been moved
=> Update Blazor link

README.md
=> Adding in JWebAssembly

README.md
I've added an entry to a programming language I've made.. :)
=> Added Poetry

README.md
Added JavaScipt section and Duktape
=> Added JavaScipt section and Duktape

README.md
=> add run.rb to the ruby section

README.md
I found this list, and had same problem as #13.  Adding a legend will make the meaning behind the emojis more explicit.
=> Add legend for emojis

README.md
=> the windows 10 calculator now runs in WebAssembly

README.md
This is a pet project I've been working on for a while. It still has a few bugs that I'm working out, but it's functional.
Here's a list to an online version that folks can play with: https://eel.capt.dev/
I'm not sure if amateur compilers like this are appropriate for this list or not. If not, feel free not to merge this pull request. 
Thanks for the great list!
=> Add eel-wasm

README.md
Hey @appcypher 
just fixing some typos in the C++ section
Cheers!
=> Fixing typos in C++ section

README.md
Hey @appcypher
just a typo in the PIB entry.
Cheers!
=> Typo: broswer -> browser

README.md
wah code was last touched four years ago
=> wah~ `Unmaintained`

README.md
`Ballerina `is an open-source programming language for the cloud that makes it easier to use, combine, and create network services.
The `nBallerina `compiler is the native compiler for `Ballerina `Language. This is the `wasm `backend for nBallerina compiler
=> Add `Ballerina` to wasm compiler

README.md
Hey there!
I noticed that Crystal's starting to target WASM directly, so I figured I'd submit it here 👌
=> Add the Crystal programming language

README.md
This is a simplified C to Web Assembly compiled, based on Antlr4 parser
=> Added `c4wa`

README.md
F# uses Bolero since years in production.
=> F# > hatched

README.md
The directory has been renamed.
Refs: https://github.com/micropython/micropython/pull/9073
=> Fix MicroPython link

README.md
Added interesting QuickJs - related projects: quickjs-emscripten and wasmedge-quickjs.
=> Added quickjs-emscripten and wasmedge-quickjs

README.md
Hey, thanks for creating this list! It would be great if you could include Lox, a teaching language popularized by the book [Crafting Interpreters](https://craftinginterpreters.com/).
=> Add section for Lox

README.md
From the luwa repo: `Luwa's end goal is to JIT to WASM`
=> fix luwa description

README.md
Added Ada, Virgil, Rise-JVM, scheme.wasm (also mentioned in #108), Wisp (also mentioned in #108), Wacl.
Also cry-wasm and micropython-wasm.
=> Added Ada, Virgil, Rise-JVM, scheme.wasm, Wisp, Wacl

README.md
=> Fix the Dart section title

README.md
add Brainfuck interpreter written in 凹语言/Wa-lang
=> Add Brainfuck interpreter written in 凹语言/Wa-lang
